<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dapr.Actors\Dapr.Actors.csproj" />
    <ProjectReference Include="..\..\src\Dapr.Actors.AspNetCore\Dapr.Actors.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Dapr.Actors.Next.Abstractions\Dapr.Actors.Next.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Dapr.Actors.Next.Core\Dapr.Actors.Next.Core.csproj" />
    <ProjectReference Include="..\..\src\Dapr.Actors.Next.SourceGenerators\Dapr.Actors.Next.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
