<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecretManagement.FSharp.Sample.Types\SecretManagement.FSharp.Sample.Types.fsproj" />
    <ProjectReference Include="..\SecretManagement.FSharp.Sample.Glue\SecretManagement.FSharp.Sample.Glue.csproj" />
  </ItemGroup>

</Project>
