<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Dapr.Actors.Next.Abstractions\Dapr.Actors.Next.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\src\Dapr.Actors.Next.Core\Dapr.Actors.Next.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Dapr.Actors.Next.Interpreted\Dapr.Actors.Next.Interpreted.csproj" />
    <ProjectReference Include="..\..\..\src\Dapr.Workflow\Dapr.Workflow.csproj" />
    <ProjectReference Include="..\..\..\src\Dapr.Workflow.Abstractions\Dapr.Workflow.Abstractions.csproj" />
  </ItemGroup>

</Project>
