using System;
using System.Text.Json;
using Dapr.Client;
using Dapr.Client.Autogen.Grpc.v1;
using Grpc.Net.Client;
using GrpcServiceSample.Models;
using Autogenerated = Dapr.AppCallback.Autogen.Grpc.v1;

namespace GrpcClient
{
    class Program
    {
        static readonly JsonSerializerOptions jsonOptions = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            AppContext.SetSwitch(
                    "System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

            var channel = GrpcChannel.ForAddress("http://localhost:5000");
            var client = new Autogenerated.AppCallback.AppCallbackClient(channel);

            var data = TypeConverters.ToAny(new GetAccountInput { Id = "abc" }, jsonOptions);
            var request = new InvokeRequest { Method = "getaccount", Data = data };
            var response = client.OnInvoke(request);
            var output = TypeConverters.FromAny<GetAccountOutput>(response.Data, jsonOptions);
            Console.WriteLine("Balance is: " + output.Balance);

            Console.ReadLine();
        }
    }
}
