apiVersion: dapr.io/v1alpha1
kind: Component
metadata: 
  name: azurekeyvault
spec:
  type: crypto.azure.keyvault
  metadata:
  - name: vaultName  
    value: "<changeMe>"
  - name: azureEnvironment
    value: AZUREPUBLICCLOUD
  - name: azureTenantId
    secretKeyRef:
      name: read_azure_tenant_id
      key: read_azure_tenant_id
  - name: azureClientId
    secretKeyRef:
      name: read_azure_client_id
      key: read_azure_client_id
  - name: azureClientSecret
    secretKeyRef:
      name: read_azure_client_secret
      key: read_azure_client_secret
auth:
  secureStore: envvar-secret-store    