// ------------------------------------------------------------------------
// Copyright 2025 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using Dapr.Common.Serialization;
using Microsoft.Extensions.Logging;

namespace Dapr.VirtualActors.Runtime.Client;

/// <summary>
/// gRPC-backed proxy factory that creates actor proxies resolved from the DI container.
/// </summary>
/// <remarks>
/// This replaces the legacy <c>ActorProxyFactory</c> and its static
/// <c>ActorProxy.Create</c> pattern. Instances are registered as singletons
/// in DI and injected where needed.
/// </remarks>
internal sealed partial class GrpcVirtualActorProxyFactory : IVirtualActorProxyFactory
{
    private readonly Grpc.DaprGrpcActorClient _grpcClient;
    private readonly IDaprSerializer _serializer;
    private readonly ILogger<GrpcVirtualActorProxyFactory> _logger;

    public GrpcVirtualActorProxyFactory(
        Grpc.DaprGrpcActorClient grpcClient,
        IDaprSerializer serializer,
        ILogger<GrpcVirtualActorProxyFactory> logger)
    {
        ArgumentNullException.ThrowIfNull(grpcClient);
        ArgumentNullException.ThrowIfNull(serializer);
        ArgumentNullException.ThrowIfNull(logger);

        _grpcClient = grpcClient;
        _serializer = serializer;
        _logger = logger;
    }

    /// <inheritdoc />
    public TActorInterface CreateProxy<TActorInterface>(VirtualActorId actorId, string? actorType = null)
        where TActorInterface : IVirtualActor
    {
        actorType ??= typeof(TActorInterface).Name;
        if (actorType.StartsWith('I') && actorType.Length > 1 && char.IsUpper(actorType[1]))
        {
            actorType = actorType[1..]; // Strip leading 'I' from interface name
        }

        LogCreatingProxy(actorType, actorId.GetId());

        // The strongly-typed proxy is generated by the source generator.
        // For now, we create a dynamic proxy that uses the weakly-typed path.
        var proxy = new GrpcVirtualActorProxy(_grpcClient, _serializer, actorId, actorType);

        // Cast via interface — works if TActorInterface is IVirtualActorProxy or if
        // the source generator has produced a concrete implementation.
        if (proxy is TActorInterface typed)
        {
            return typed;
        }

        throw new InvalidOperationException(
            $"Cannot create strongly-typed proxy for '{typeof(TActorInterface).Name}'. " +
            $"Use [GenerateActorClient] on the interface or use CreateProxy(actorId, actorType) for weakly-typed access.");
    }

    /// <inheritdoc />
    public IVirtualActorProxy CreateProxy(VirtualActorId actorId, string actorType)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(actorType);
        LogCreatingProxy(actorType, actorId.GetId());
        return new GrpcVirtualActorProxy(_grpcClient, _serializer, actorId, actorType);
    }

    [LoggerMessage(Level = LogLevel.Debug, Message = "Creating proxy for actor {ActorType}/{ActorId}")]
    private partial void LogCreatingProxy(string actorType, string actorId);
}
