<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <DaprWorkflowVersioningScanReferences>true</DaprWorkflowVersioningScanReferences>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="DaprWorkflowVersioningScanReferences" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorkflowVersioning.FSharp.Workflows\WorkflowVersioning.FSharp.Workflows.fsproj" />
    <ProjectReference Include="..\..\..\..\src\Dapr.Workflow\Dapr.Workflow.csproj" />
    <ProjectReference Include="..\..\..\..\src\Dapr.Workflow.Versioning.Abstractions\Dapr.Workflow.Versioning.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\src\Dapr.Workflow.Versioning.Runtime\Dapr.Workflow.Versioning.Runtime.csproj" />
    <ProjectReference Include="..\..\..\..\src\Dapr.Workflow.Versioning.Generators\Dapr.Workflow.Versioning.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

</Project>