<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="DaprSecretsManagementScanReferences" />
  </ItemGroup>
  <PropertyGroup>
    <DaprSecretsManagementScanReferences Condition="'$(DaprSecretsManagementScanReferences)' == ''">false</DaprSecretsManagementScanReferences>
  </PropertyGroup>
</Project>
