<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Moq" />
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="xunit.v3.extensibility.core" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Dapr.Messaging.Abstractions\Dapr.Messaging.Abstractions.csproj" />
      <ProjectReference Include="..\..\src\Dapr.Messaging.Runtime\Dapr.Messaging.Runtime.csproj" />
      <ProjectReference Include="..\..\src\Dapr.Messaging.Generators\Dapr.Messaging.Generators.csproj"
                        OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
      <ProjectReference Include="..\..\src\Dapr.Testcontainers\Dapr.Testcontainers.csproj" />
    </ItemGroup>

</Project>