// ------------------------------------------------------------------------
// Copyright 2025 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using Dapr.Common;
using Dapr.Common.Serialization;
using Microsoft.Extensions.Configuration;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.StateManagement;

/// <summary>
/// Builds a <see cref="DaprStateManagementClient"/>.
/// </summary>
/// <remarks>
/// <para>
/// Use this builder when you need to create a <see cref="DaprStateManagementClient"/> manually,
/// outside of dependency injection. For DI-based scenarios, use
/// <c>DaprStateManagementServiceCollectionExtensions.AddDaprStateManagementClient</c> instead.
/// </para>
/// </remarks>
/// <param name="configuration">
/// An optional <see cref="IConfiguration"/> instance used to read Dapr defaults such as the
/// API token and endpoint addresses from the environment.
/// </param>
public sealed class DaprStateManagementClientBuilder(IConfiguration? configuration = null)
    : DaprGenericClientBuilder<DaprStateManagementClient>(configuration)
{
    /// <summary>
    /// Builds a new <see cref="DaprStateManagementClient"/> from the current builder configuration.
    /// </summary>
    /// <returns>A configured <see cref="DaprStateManagementClient"/> instance.</returns>
    public override DaprStateManagementClient Build()
    {
        var deps = this.BuildDaprClientDependencies(typeof(DaprStateManagementClient).Assembly);
        var grpcClient = new Autogenerated.Dapr.DaprClient(deps.channel);
        return new DaprStateManagementGrpcClient(
            grpcClient,
            deps.httpClient,
            new JsonDaprSerializer(this.JsonSerializerOptions),
            deps.daprApiToken);
    }
}
