// ------------------------------------------------------------------------
// Copyright 2024 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using System.Threading.Channels;
using Dapr.AppCallback.Autogen.Grpc.v1;
using Grpc.Core;
using P = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.Messaging.PublishSubscribe;

/// <summary>
/// A thread-safe implementation of a receiver for messages from a specified Dapr publish/subscribe component and
/// topic.
/// </summary>
/// <remarks>
/// This receiver manages a bidirectional gRPC stream to the Dapr sidecar, decoupling message receipt from
/// message processing via internal channels. Background tasks for fetching data, processing acknowledgements,
/// and handling topic messages are supervised by <see cref="RunSubscriptionAsync"/> which aggregates their
/// faults and surfaces them through <see cref="Completion"/>.
/// </remarks>
internal sealed class PublishSubscribeReceiver : IDaprSubscription
{
    /// <summary>
    /// Shared options for unbounded channels enforcing single-reader, single-writer semantics.
    /// </summary>
    private static readonly UnboundedChannelOptions UnboundedChannelOptions = new()
    {
        SingleWriter = true, SingleReader = true
    };

    /// <summary>
    /// The name of the Dapr publish/subscribe component.
    /// </summary>
    private readonly string _pubSubName;
    /// <summary>
    /// The name of the topic to subscribe to.
    /// </summary>
    private readonly string _topicName;
    /// <summary>
    /// Options allowing the behavior of the receiver to be configured.
    /// </summary>
    private readonly DaprSubscriptionOptions _options;
    /// <summary>
    /// A channel used to decouple the messages received from the sidecar from their consumption.
    /// </summary>
    private readonly Channel<TopicMessage> _topicMessagesChannel;
    /// <summary>
    /// A channel maintaining acknowledgements for each message awaiting submission to the sidecar.
    /// </summary>
    private readonly Channel<TopicAcknowledgement> _acknowledgementsChannel =
        Channel.CreateUnbounded<TopicAcknowledgement>(UnboundedChannelOptions);
    /// <summary>
    /// The handler delegate responsible for processing the topic messages.
    /// </summary>
    private readonly TopicMessageHandler _messageHandler;
    /// <summary>
    /// A reference to the autogenerated gRPC Dapr client used to establish the subscription stream.
    /// </summary>
    private readonly P.Dapr.DaprClient _client;

    /// <summary>
    /// Flag that prevents the receiver from initializing the subscription more than once concurrently.
    /// Reset to 0 in the supervisor's <c>finally</c> block so the caller can re-subscribe after any termination.
    /// </summary>
    private int _hasInitialized;
    /// <summary>
    /// Flag that ensures the instance is only disposed a single time.
    /// </summary>
    private bool _isDisposed;
    /// <summary>
    /// The supervisor task returned by <see cref="RunSubscriptionAsync"/>, exposed to callers via
    /// <see cref="Completion"/>.
    /// </summary>
    private Task? _subscriptionTask;
    /// <summary>
    /// Cancellation source used by <see cref="DisposeAsync"/> to unblock background tasks during shutdown.
    /// </summary>
    private CancellationTokenSource? _disposeCts;
    /// <summary>
    /// Linked cancellation source combining the caller's token and <see cref="_disposeCts"/> so that either
    /// cancellation or disposal unblocks all background tasks.
    /// </summary>
    private CancellationTokenSource? _linkedCts;

    /// <summary>
    /// Exposes the completion of the topic messages channel for testing purposes.
    /// </summary>
    internal Task TopicMessagesChannelCompletion => _topicMessagesChannel.Reader.Completion;

    /// <summary>
    /// Exposes the completion of the acknowledgements channel for testing purposes.
    /// </summary>
    internal Task AcknowledgementsChannelCompletion => _acknowledgementsChannel.Reader.Completion;

    /// <summary>
    /// A task that completes when the subscription's background processing finishes.
    /// </summary>
    /// <remarks>
    /// Faults with a <see cref="DaprException"/> if a background task errors and no
    /// <see cref="DaprSubscriptionOptions.ErrorHandler"/> is configured. If the handler itself throws, the
    /// task faults with an <see cref="AggregateException"/> combining the original fault and the handler
    /// failure. Completes normally when the background tasks finish without error or when all faults are
    /// cancellation-related.
    /// </remarks>
    public Task Completion => _subscriptionTask ?? Task.CompletedTask;

    /// <summary>
    /// Constructs a new instance of a <see cref="PublishSubscribeReceiver"/>.
    /// </summary>
    /// <param name="pubSubName">The name of the Dapr publish/subscribe component.</param>
    /// <param name="topicName">The name of the topic to subscribe to.</param>
    /// <param name="options">Options allowing the behavior of the receiver to be configured.</param>
    /// <param name="handler">The delegate reflecting the action to take upon messages received by the subscription.</param>
    /// <param name="client">A reference to the gRPC Dapr client used to establish the subscription stream.</param>
    internal PublishSubscribeReceiver(string pubSubName, string topicName, DaprSubscriptionOptions options,
        TopicMessageHandler handler, P.Dapr.DaprClient client)
    {
        this._client = client;
        this._pubSubName = pubSubName;
        this._topicName = topicName;
        this._options = options;
        this._messageHandler = handler;
        _topicMessagesChannel = options.MaximumQueuedMessages is > 0
            ? Channel.CreateBounded<TopicMessage>(new BoundedChannelOptions((int)options.MaximumQueuedMessages)
            {
                SingleReader = true, SingleWriter = true, FullMode = BoundedChannelFullMode.Wait
            })
            : Channel.CreateUnbounded<TopicMessage>(UnboundedChannelOptions);
    }

    /// <summary>
    /// Dynamically subscribes to messages on a pub/sub topic provided by the Dapr sidecar.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token used to cancel the initial stream establishment
    /// and subsequent background processing.</param>
    /// <returns>A task that completes once the subscription has been initiated. Background processing
    /// continues on the supervisor task exposed via <see cref="Completion"/>.</returns>
    /// <exception cref="ObjectDisposedException">Thrown if the receiver has been disposed.</exception>
    /// <exception cref="DaprException">Thrown when the gRPC stream cannot be established (e.g. sidecar
    /// unavailable). The original <see cref="RpcException"/> is available via
    /// <see cref="Exception.InnerException"/>.</exception>
    /// <remarks>
    /// Calling this method more than once on the same instance without an intervening termination or
    /// disposal is a no-op (the second call returns immediately). After the supervisor terminates — whether
    /// due to a fault, cancellation, or clean stream end — <see cref="_hasInitialized"/> is reset, allowing
    /// the caller to re-subscribe.
    /// </remarks>
    internal Task SubscribeAsync(CancellationToken cancellationToken = default)
    {
        ObjectDisposedException.ThrowIf(_isDisposed, this);
        cancellationToken.ThrowIfCancellationRequested();

        if (Interlocked.Exchange(ref _hasInitialized, 1) == 1)
        {
            return Task.CompletedTask;
        }

        AsyncDuplexStreamingCall<P.SubscribeTopicEventsRequestAlpha1, P.SubscribeTopicEventsResponseAlpha1> stream;
        try
        {
            stream = _client.SubscribeTopicEventsAlpha1(cancellationToken: cancellationToken);
        }
        catch (RpcException ex)
        {
            Interlocked.Exchange(ref _hasInitialized, 0);
            throw new DaprException(
                $"Failed to establish a subscription stream for topic '{_topicName}' on pubsub '{_pubSubName}'. Ensure the Dapr sidecar is available.",
                ex);
        }
        catch (Exception)
        {
            Interlocked.Exchange(ref _hasInitialized, 0);
            throw;
        }

        _disposeCts = new CancellationTokenSource();
        _linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
        _subscriptionTask = RunSubscriptionAsync(stream, _linkedCts.Token);
        return Task.CompletedTask;
    }

    /// <summary>
    /// Supervisor that runs the three background tasks concurrently and handles their faults in a single
    /// try/catch, eliminating the need for per-task continuations, dedupe flags, or cached faults.
    /// </summary>
    /// <param name="stream">The bidirectional gRPC streaming call to the Dapr sidecar.</param>
    /// <param name="cancellationToken">Linked cancellation token combining the caller's token and the
    /// disposal token. When any task faults or is cancelled, this token is cancelled to unblock the
    /// remaining tasks so the <c>Task.WhenAll</c> call completes promptly.</param>
    /// <returns>A task representing the supervisor's lifecycle. Faults with a <see cref="DaprException"/>
    /// when no <see cref="DaprSubscriptionOptions.ErrorHandler"/> is configured, or with an
    /// <see cref="AggregateException"/> when the handler itself throws.</returns>
    /// <remarks>
    /// When multiple non-cancellation exceptions occur, they are wrapped in an <see cref="AggregateException"/>
    /// as the inner exception of the <see cref="DaprException"/>. If every fault is cancellation-related, the
    /// supervisor completes normally. The <see cref="_hasInitialized"/> flag is reset in the <c>finally</c>
    /// block so the caller can re-subscribe after any termination.
    /// </remarks>
    private async Task RunSubscriptionAsync(
        AsyncDuplexStreamingCall<P.SubscribeTopicEventsRequestAlpha1, P.SubscribeTopicEventsResponseAlpha1> stream,
        CancellationToken cancellationToken)
    {
        var fetchTask = FetchDataFromSidecarAsync(stream, _topicMessagesChannel.Writer, cancellationToken);
        var ackTask = ProcessAcknowledgementChannelMessagesAsync(stream, cancellationToken);
        var topicTask = ProcessTopicChannelMessagesAsync(cancellationToken);

        // When any task faults or is cancelled, cancel the linked CTS to unblock the remaining
        // tasks so Task.WhenAll completes promptly instead of waiting indefinitely.
        foreach (var t in (Task[])[fetchTask, ackTask, topicTask])
        {
            _ = t.ContinueWith(
                static (_, state) =>
                {
                    try { (state as CancellationTokenSource)?.Cancel(); }
                    catch (ObjectDisposedException) { }
                },
                _linkedCts, CancellationToken.None,
                TaskContinuationOptions.NotOnRanToCompletion, TaskScheduler.Default);
        }

        var allTasks = Task.WhenAll(fetchTask, ackTask, topicTask);

        try
        {
            await allTasks.ConfigureAwait(false);
        }
        catch (Exception)
        {
            // If the supervisor task was cancelled (not faulted), clean shutdown.
            if (allTasks.Exception is null)
            {
                return;
            }

            var innerExceptions = allTasks.Exception.InnerExceptions;

            // If every fault is a cancellation, clean shutdown.
            if (innerExceptions.All(e => e is OperationCanceledException))
            {
                return;
            }

            // Collect all non-cancellation exceptions; wrap in AggregateException if more than one.
            var nonOce = innerExceptions.Where(e => e is not OperationCanceledException).ToList();
            Exception innerException = nonOce.Count switch
            {
                0 => (Exception)allTasks.Exception ?? new InvalidOperationException("Unknown subscription error."),
                1 => nonOce[0],
                _ => new AggregateException(nonOce)
            };

            var daprException = new DaprException(
                $"An error occurred during an active subscription to topic '{_topicName}' on pubsub '{_pubSubName}'.",
                innerException);

            if (_options.ErrorHandler is null)
            {
                throw daprException;
            }

            try
            {
                await _options.ErrorHandler.Invoke(daprException).ConfigureAwait(false);
            }
            catch (Exception handlerEx)
            {
                throw new AggregateException(
                    $"The SubscriptionErrorHandler for topic '{_topicName}' on pubsub '{_pubSubName}' threw while handling a prior fault.",
                    daprException, handlerEx);
            }
        }
        finally
        {
            // Reset so the caller can re-subscribe after any termination (handled fault, unhandled fault, or clean end).
            Interlocked.Exchange(ref _hasInitialized, 0);
            stream.Dispose();
        }
    }

    /// <summary>
    /// Writes a topic message directly to the internal messages channel for testing purposes.
    /// </summary>
    /// <param name="message">The topic message to write.</param>
    /// <returns>A task that completes when the message has been written to the channel.</returns>
    internal async Task WriteMessageToChannelAsync(TopicMessage message)
    {
        await _topicMessagesChannel.Writer.WriteAsync(message);
    }

    /// <summary>
    /// Writes an acknowledgement directly to the internal acknowledgements channel for testing purposes.
    /// </summary>
    /// <param name="acknowledgement">The acknowledgement to write.</param>
    /// <returns>A task that completes when the acknowledgement has been written to the channel.</returns>
    internal async Task WriteAcknowledgementToChannelAsync(TopicAcknowledgement acknowledgement)
    {
        await _acknowledgementsChannel.Writer.WriteAsync(acknowledgement);
    }

    /// <summary>
    /// Acknowledges the indicated message back to the Dapr sidecar with an indicated behavior to take
    /// on the message.
    /// </summary>
    /// <param name="messageId">The identifier of the message the behavior is in reference to.</param>
    /// <param name="behavior">The behavior to take on the message as indicated by either the message
    /// handler or timeout message handling configuration.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task that completes when the acknowledgement has been written to the acknowledgements
    /// channel.</returns>
    /// <exception cref="InvalidOperationException">Thrown when <paramref name="behavior"/> is not a
    /// recognized <see cref="TopicResponseAction"/> value.</exception>
    private async Task AcknowledgeMessageAsync(string messageId, TopicResponseAction behavior,
        CancellationToken cancellationToken)
    {
        var action = behavior switch
        {
            TopicResponseAction.Success => TopicEventResponse.Types.TopicEventResponseStatus.Success,
            TopicResponseAction.Retry => TopicEventResponse.Types.TopicEventResponseStatus.Retry,
            TopicResponseAction.Drop => TopicEventResponse.Types.TopicEventResponseStatus.Drop,
            _ => throw new InvalidOperationException(
                $"Unrecognized topic acknowledgement action: {behavior}")
        };

        var acknowledgement = new TopicAcknowledgement(messageId, action);
        await _acknowledgementsChannel.Writer.WriteAsync(acknowledgement, cancellationToken);
    }

    /// <summary>
    /// Processes each acknowledgement from the acknowledgement channel reader as it's populated,
    /// writing it to the gRPC request stream back to the Dapr sidecar.
    /// </summary>
    /// <param name="messageStream">The bidirectional gRPC stream used to interact with the Dapr sidecar.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task that completes when the acknowledgement channel reader has finished (i.e. the
    /// channel writer has been completed).</returns>
    private async Task ProcessAcknowledgementChannelMessagesAsync(
        AsyncDuplexStreamingCall<P.SubscribeTopicEventsRequestAlpha1, P.SubscribeTopicEventsResponseAlpha1> messageStream,
        CancellationToken cancellationToken)
    {
        await foreach (var acknowledgement in _acknowledgementsChannel.Reader.ReadAllAsync(cancellationToken))
        {
            await messageStream.RequestStream.WriteAsync(new P.SubscribeTopicEventsRequestAlpha1
            {
                EventProcessed = new P.SubscribeTopicEventsRequestProcessedAlpha1
                {
                    Id = acknowledgement.MessageId,
                    Status = new TopicEventResponse { Status = acknowledgement.Action }
                }
            }, cancellationToken);
        }
    }

    /// <summary>
    /// Processes each topic message from the messages channel as it's populated, invoking the message
    /// handler and writing the resulting acknowledgement back to the sidecar.
    /// </summary>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task that completes when the topic messages channel reader has finished (i.e. the
    /// channel writer has been completed).</returns>
    /// <remarks>
    /// Each message is processed with a linked cancellation token that fires after the configured
    /// <see cref="MessageHandlingPolicy.TimeoutDuration"/>. If the handler does not complete within the
    /// timeout, the <see cref="MessageHandlingPolicy.DefaultResponseAction"/> is used to acknowledge the
    /// message instead.
    /// </remarks>
    private async Task ProcessTopicChannelMessagesAsync(CancellationToken cancellationToken)
    {
        await foreach (var message in _topicMessagesChannel.Reader.ReadAllAsync(cancellationToken))
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
            cts.CancelAfter(_options.MessageHandlingPolicy.TimeoutDuration);

            var messageAction = await _messageHandler(message, cts.Token);

            try
            {
                await AcknowledgeMessageAsync(message.Id, messageAction, cancellationToken);
            }
            catch (OperationCanceledException)
            {
                await AcknowledgeMessageAsync(message.Id, _options.MessageHandlingPolicy.DefaultResponseAction,
                    cancellationToken);
            }
        }
    }

    /// <summary>
    /// Retrieves the subscription stream data from the Dapr sidecar and writes each received event
    /// message to the topic messages channel.
    /// </summary>
    /// <param name="stream">The stream connection to and from the Dapr sidecar instance.</param>
    /// <param name="channelWriter">The channel writer instance to write received messages to.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A task that completes when the response stream has been fully read or cancelled.</returns>
    /// <remarks>
    /// Sends the initial subscription request (including pub/sub name, topic, dead-letter topic, and
    /// metadata) before reading the response stream. Messages with a null <c>EventMessage</c> are skipped.
    /// Channel write failures are silently swallowed because they indicate the channel was completed
    /// during <see cref="DisposeAsync"/>.
    /// </remarks>
    private async Task FetchDataFromSidecarAsync(
        AsyncDuplexStreamingCall<P.SubscribeTopicEventsRequestAlpha1, P.SubscribeTopicEventsResponseAlpha1> stream,
        ChannelWriter<TopicMessage> channelWriter, CancellationToken cancellationToken)
    {
        var initialRequest = new P.SubscribeTopicEventsRequestInitialAlpha1()
        {
            PubsubName = _pubSubName, DeadLetterTopic = _options.DeadLetterTopic ?? string.Empty, Topic = _topicName
        };

        if (_options.Metadata.Count > 0)
        {
            foreach (var (key, value) in _options.Metadata)
            {
                initialRequest.Metadata.Add(key, value);
            }
        }

        await stream.RequestStream.WriteAsync(
            new P.SubscribeTopicEventsRequestAlpha1 { InitialRequest = initialRequest }, cancellationToken);

        await foreach (var response in stream.ResponseStream.ReadAllAsync(cancellationToken))
        {
            if (response?.EventMessage is null)
            {
                continue;
            }

            var message =
                new TopicMessage(response.EventMessage.Id, response.EventMessage.Source, response.EventMessage.Type,
                    response.EventMessage.SpecVersion, response.EventMessage.DataContentType,
                    response.EventMessage.Topic, response.EventMessage.PubsubName)
                {
                    Path = response.EventMessage.Path,
                    Extensions = response.EventMessage.Extensions.Fields.ToDictionary(f => f.Key, kvp => kvp.Value),
                    Data = response.EventMessage.Data.ToByteArray()
                };

            try
            {
                await channelWriter.WaitToWriteAsync(cancellationToken);
                await channelWriter.WriteAsync(message, cancellationToken);
            }
            catch (Exception)
            {
                // Channel writer completed during DisposeAsync — stop writing.
            }
        }
    }

    /// <summary>
    /// Disposes the various resources associated with the instance, including completing both internal
    /// channels, cancelling background tasks, and waiting for the supervisor to terminate.
    /// </summary>
    /// <returns>A value task that completes when disposal is finished.</returns>
    /// <remarks>
    /// Completes both channel writers to unblock readers, cancels the disposal CTS to unblock background
    /// tasks waiting on the gRPC stream, then waits up to
    /// <see cref="DaprSubscriptionOptions.MaximumCleanupTimeout"/> for the supervisor task to terminate.
    /// Any exceptions from the supervisor during this wait are suppressed.
    /// </remarks>
    public async ValueTask DisposeAsync()
    {
        if (_isDisposed)
        {
            return;
        }

        _isDisposed = true;

        _topicMessagesChannel.Writer.TryComplete();
        _acknowledgementsChannel.Writer.TryComplete();

        // Cancel to unblock any background tasks waiting on the gRPC stream or channels.
        _disposeCts?.Cancel();

        if (_subscriptionTask is not null)
        {
            try
            {
                await _subscriptionTask.WaitAsync(_options.MaximumCleanupTimeout).ConfigureAwait(false);
            }
            catch (TimeoutException) { }
            catch (OperationCanceledException) { }
            catch (Exception) { }
        }

        _linkedCts?.Dispose();
        _disposeCts?.Dispose();
    }

    /// <summary>
    /// Reflects the action to take on a given message identifier when acknowledging back to the sidecar.
    /// </summary>
    /// <param name="MessageId">The identifier of the message.</param>
    /// <param name="Action">The action to take on the message in the acknowledgement request.</param>
    internal sealed record TopicAcknowledgement(string MessageId, TopicEventResponse.Types.TopicEventResponseStatus Action);
}
