// ------------------------------------------------------------------------
//  Copyright 2026 The Dapr Authors
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ------------------------------------------------------------------------

using Dapr.Common;
using Microsoft.Extensions.Configuration;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.SecretsManagement;

/// <summary>
/// Builds a <see cref="DaprSecretsManagementClient"/> instance with the specified configuration.
/// </summary>
/// <param name="configuration">An optional <see cref="IConfiguration"/> instance used to resolve default settings.</param>
public sealed class DaprSecretsManagementClientBuilder(IConfiguration? configuration = null)
    : DaprGenericClientBuilder<DaprSecretsManagementClient>(configuration)
{
    /// <summary>
    /// Builds the <see cref="DaprSecretsManagementClient"/> instance from the properties configured on this builder.
    /// </summary>
    /// <returns>A new <see cref="DaprSecretsManagementClient"/> instance.</returns>
    public override DaprSecretsManagementClient Build()
    {
        var daprClientDependencies = this.BuildDaprClientDependencies(typeof(DaprSecretsManagementClient).Assembly);
        var client = new Autogenerated.Dapr.DaprClient(daprClientDependencies.channel);
        var runtimeCapabilities = new DaprRuntimeCapabilities(daprClientDependencies.channel);
        return new DaprSecretsManagementGrpcClient(client, daprClientDependencies.httpClient, runtimeCapabilities, daprClientDependencies.daprApiToken);
    }
}
