// ------------------------------------------------------------------------
//  Copyright 2026 The Dapr Authors
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ------------------------------------------------------------------------

using Dapr.Common;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1.Dapr;

namespace Dapr.SecretsManagement;

/// <summary>
/// <para>
/// Defines client operations for managing Dapr secrets. Use <see cref="DaprSecretsManagementClientBuilder"/>
/// to create a <see cref="DaprSecretsManagementClient"/> or register for use with dependency injection via
/// <see cref="Extensions.DaprSecretsManagementServiceCollectionExtensions.AddDaprSecretsManagementClient"/>.
/// </para>
/// <para>
/// Implementations of <see cref="DaprSecretsManagementClient"/> implement <see cref="IDisposable"/> because the
/// client accesses network resources. For best performance, create a single long-lived client instance and share
/// it for the lifetime of the application. This is done for you if created via the DI extensions. Avoid creating
/// and disposing a client instance for each operation that the application performs — this can lead to socket
/// exhaustion and other problems.
/// </para>
/// </summary>
public abstract class DaprSecretsManagementClient(
    Autogenerated.DaprClient client,
    HttpClient httpClient,
    string? daprApiToken = null) : IDaprClient
{
    private bool disposed;

    /// <summary>
    /// The HTTP client used by the client for calling the Dapr runtime.
    /// </summary>
    /// <remarks>
    /// Property exposed for testing purposes.
    /// </remarks>
    internal readonly HttpClient HttpClient = httpClient;

    /// <summary>
    /// The Dapr API token value.
    /// </summary>
    /// <remarks>
    /// Property exposed for testing purposes.
    /// </remarks>
    internal readonly string? DaprApiToken = daprApiToken;

    /// <summary>
    /// The autogenerated Dapr gRPC client.
    /// </summary>
    /// <remarks>
    /// Property exposed for testing purposes.
    /// </remarks>
    internal Autogenerated.DaprClient Client { get; } = client;

    /// <summary>
    /// Gets the secret value for a specific key from the specified secret store.
    /// </summary>
    /// <param name="storeName">The name of the Dapr secret store component.</param>
    /// <param name="key">The secret key to retrieve.</param>
    /// <param name="metadata">
    /// An optional collection of metadata key-value pairs that will be provided to the secret store component.
    /// The valid metadata keys and values are determined by the type of secret store used.
    /// </param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> that can be used to cancel the operation.</param>
    /// <returns>
    /// A <see cref="Task{T}"/> that resolves to a <see cref="Dictionary{TKey, TValue}"/> containing the secret
    /// data. Some secret stores (such as Kubernetes) can store multiple values per key — each entry in the
    /// dictionary represents one such value.
    /// </returns>
    public abstract Task<IReadOnlyDictionary<string, string>> GetSecretAsync(
        string storeName,
        string key,
        IReadOnlyDictionary<string, string>? metadata = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets all secret values that the application is allowed to access from the specified secret store.
    /// </summary>
    /// <param name="storeName">The name of the Dapr secret store component.</param>
    /// <param name="metadata">
    /// An optional collection of metadata key-value pairs that will be provided to the secret store component.
    /// The valid metadata keys and values are determined by the type of secret store used.
    /// </param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> that can be used to cancel the operation.</param>
    /// <returns>
    /// A <see cref="Task{T}"/> that resolves to a nested dictionary. The outer key is the secret name; the inner
    /// dictionary contains one or more key-value pairs representing the secret data.
    /// </returns>
    public abstract Task<IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>>> GetBulkSecretAsync(
        string storeName,
        IReadOnlyDictionary<string, string>? metadata = null,
        CancellationToken cancellationToken = default);

    /// <inheritdoc />
    public void Dispose()
    {
        if (!this.disposed)
        {
            Dispose(disposing: true);
            this.disposed = true;
        }
    }

    /// <summary>
    /// Disposes the resources associated with the object.
    /// </summary>
    /// <param name="disposing"><see langword="true"/> if called by a call to the <see cref="Dispose()"/> method; otherwise <see langword="false"/>.</param>
    protected virtual void Dispose(bool disposing)
    {
    }
}
