### Create new order
POST http://localhost:10080/orders
Content-Type: application/json

{"name": "Paperclips", "totalCost": 99.95, "quantity": 1}

### Query placeholder
GET http://localhost:10080/orders/XXX