<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="DaprStateManagementScanReferences" />
  </ItemGroup>
  <PropertyGroup>
    <DaprStateManagementScanReferences Condition="'$(DaprStateManagementScanReferences)' == ''">false</DaprStateManagementScanReferences>
  </PropertyGroup>
</Project>
