// ------------------------------------------------------------------------
//  Copyright 2025 The Dapr Authors
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//      http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ------------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;
using Dapr.Common;
using Microsoft.Extensions.Configuration;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.DistributedLock.Extensions;

/// <summary>
/// Builds a <see cref="DaprDistributedLockClient"/>.
/// </summary>
/// <param name="configuration"></param>
[Experimental("DAPR_DISTRIBUTEDLOCK", UrlFormat = "https://docs.dapr.io/developing-applications/building-blocks/distributed-lock/distributed-lock-api-overview/")]
public sealed class DaprDistributedLockBuilder(IConfiguration? configuration = null) : DaprGenericClientBuilder<DaprDistributedLockClient>(configuration)
{
    /// <summary>
    /// Builds the client instance from the properties of the builder.
    /// </summary>
    /// <returns>The dapr client instance.</returns>
    public override DaprDistributedLockClient Build()
    {
        var daprClientDependencies = this.BuildDaprClientDependencies(typeof(DaprDistributedLockClient).Assembly);
        var client = new Autogenerated.Dapr.DaprClient(daprClientDependencies.channel);
        return new DaprDistributedLockGrpcClient(client, daprClientDependencies.httpClient, daprClientDependencies.daprApiToken);
    }
}
