using System.Text.Json.Serialization;
using Dapr.Common.JsonConverters;

namespace Dapr.AI.Conversation.ConversationRoles;

/// <summary>
/// The contents of a conversation message in the role of an assistant.
/// </summary>
public record AssistantMessage : IConversationMessage
{
    /// <summary>
    /// The role of the message.
    /// </summary>
    [JsonConverter(typeof(GenericEnumJsonConverter<MessageRole>))]
    [JsonPropertyName("role")]
    public MessageRole Role => MessageRole.Assistant;
    
    /// <summary>
    /// The optional name of the assistant.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// The content of the message.
    /// </summary>
    public IReadOnlyList<MessageContent> Content { get; set; } = [];

    /// <summary>
    /// The tool calls generated by the model, such as function calls for the client to make.
    /// </summary>
    public IReadOnlyList<ToolCallBase> ToolCalls { get; set; } = [];
}
