//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dapr.Workflow.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dapr.Workflow.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow type &apos;{0}&apos; is not registered with the dependency injection provider.
        /// </summary>
        internal static string DAPR1301MessageFormat {
            get {
                return ResourceManager.GetString("DAPR1301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow type is not registered with the dependency injection provider.
        /// </summary>
        internal static string DAPR1301Title {
            get {
                return ResourceManager.GetString("DAPR1301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow activity type &apos;{0}&apos; is not registered with the dependency injection provider.
        /// </summary>
        internal static string DAPR1302MessageFormat {
            get {
                return ResourceManager.GetString("DAPR1302MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow activity type is not registered with the dependency injection provider.
        /// </summary>
        internal static string DAPR1302Title {
            get {
                return ResourceManager.GetString("DAPR1302Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The provided input type &apos;{0}&apos; does not match the expected input type &apos;{1}&apos; for {2} &apos;{3}&apos;.
        /// </summary>
        internal static string DAPR1303MessageFormat {
            get {
                return ResourceManager.GetString("DAPR1303MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The provided input type does not match the target workflow or activity input type.
        /// </summary>
        internal static string DAPR1303Title {
            get {
                return ResourceManager.GetString("DAPR1303Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested output type &apos;{0}&apos; does not match the declared output type &apos;{1}&apos; for {2} &apos;{3}&apos;.
        /// </summary>
        internal static string DAPR1304MessageFormat {
            get {
                return ResourceManager.GetString("DAPR1304MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The requested output type does not match the target workflow or activity output type.
        /// </summary>
        internal static string DAPR1304Title {
            get {
                return ResourceManager.GetString("DAPR1304Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow &apos;{0}&apos; has constructor parameter &apos;{1}&apos; of type &apos;{2}&apos;, but dependency injection is not supported in workflow implementations. Move dependencies to a WorkflowActivity instead.
        /// </summary>
        internal static string DAPR1305MessageFormat {
            get {
                return ResourceManager.GetString("DAPR1305MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow implementations do not support dependency injection via constructors.
        /// </summary>
        internal static string DAPR1305Title {
            get {
                return ResourceManager.GetString("DAPR1305Title", resourceCulture);
            }
        }
    }
}
