kind: Service
apiVersion: v1
metadata:
  name: demoactor
  labels:
    app: demoactor
spec:
  selector:
    app: demoactor
  ports:
  - protocol: TCP
    port: 5010
    targetPort: app-port
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoactor
  labels:
    app: demoactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoactor
  template:
    metadata:
      labels:
        app: demoactor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "demoactor"
        dapr.io/app-port: "5010"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: demoactor
        # image: <your-docker-registry>/demo-actor:latest
        image: demo-actor:latest
        # if you are using docker desktop, you can use imagePullPolicy: Never to use local image
        imagePullPolicy: Never
        env:
        - name: APP_PORT
          value: "5010"
        - name: ASPNETCORE_URLS 
          value: "http://+:5010"
        ports:
        - name: app-port
          containerPort: 5010