<Project>
  <ItemGroup>
    <CompilerVisibleProperty Include="DaprWorkflowVersioningScanReferences" />
  </ItemGroup>
  <PropertyGroup>
    <DaprWorkflowVersioningScanReferences Condition="'$(DaprWorkflowVersioningScanReferences)' == ''">false</DaprWorkflowVersioningScanReferences>
  </PropertyGroup>
</Project>
