using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.Client
{
    internal class DaprSubscribeConfigurationSource : ConfigurationSource
    {
        private AsyncServerStreamingCall<Autogenerated.SubscribeConfigurationResponse> call;
        private string id = string.Empty;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="sourceStreamRequest">The request that is used to start the configuration streaming with Dapr.</param>
        /// <param name="internalClient">The internal client used to call Dapr and begin a gRPC stream.</param>
        /// <param name="callOptions">The options for the call to Dapr.</param>
        internal DaprSubscribeConfigurationSource(
            Autogenerated.Dapr.DaprClient internalClient,
            Autogenerated.SubscribeConfigurationRequest sourceStreamRequest,
            CallOptions callOptions) : base()
        {
            this.call = internalClient.SubscribeConfigurationAlpha1(sourceStreamRequest, callOptions);
        }

        /// <inheritdoc/>
        public override string Id => id;

        public override IAsyncEnumerator<IEnumerable<ConfigurationItem>> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            return new DaprSubscribeConfigurationEnumerator(call, streamId => setIdIfNullOrEmpty(streamId), cancellationToken);
        }

        private void setIdIfNullOrEmpty(string id)
        {
            if (string.IsNullOrEmpty(this.id))
            {
                this.id = id;
            }
        }
    }

    internal class DaprSubscribeConfigurationEnumerator : IAsyncEnumerator<IEnumerable<ConfigurationItem>>
    {
        private AsyncServerStreamingCall<Autogenerated.SubscribeConfigurationResponse> call;
        private Action<string> idCallback;
        private CancellationToken cancellationToken;

        internal DaprSubscribeConfigurationEnumerator(
            AsyncServerStreamingCall<Autogenerated.SubscribeConfigurationResponse> call,
            Action<string> idCallback,
            CancellationToken cancellationToken = default)
        {
            this.call = call;
            this.idCallback = idCallback;
            this.cancellationToken = cancellationToken;
        }

        /// <inheritdoc/>
        public IEnumerable<ConfigurationItem> Current
        {
            get
            {
                var current = call.ResponseStream.Current;
                if (current != null)
                {
                    idCallback(current.Id);
                    return current.Items.Select(item => new ConfigurationItem(item.Key, item.Value, item.Version, item.Metadata));
                }
                return null;
            }
        }

        /// <inheritdoc/>
        public ValueTask DisposeAsync()
        {
            call.Dispose();
            return new ValueTask();
        }

        /// <inheritdoc/>
        public async ValueTask<bool> MoveNextAsync()
        {
            return await call.ResponseStream.MoveNext(cancellationToken);
        }
    }
}
