// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
// ------------------------------------------------------------

namespace Dapr.Client
{
    using Autogenerated = Autogen.Grpc.v1;
    using Moq;

    /// <summary>
    /// This class is only needed if the app you are calling is listening on HTTP.
    /// It contains propertes that represent data may be populated for an HTTP receiver.
    /// </summary>
    public class MockAutoDaprClient : BaseDaprClient
    {
        /// <summary>
        /// This represents a collection of query strings.
        /// </summary>
        public Mock<Autogenerated.Dapr.DaprClient> Client { get; set; }


        /// <summary>
        /// This constructor
        /// </summary>
        public MockAutoDaprClient()
        {
            this.Client = new Mock<Autogenerated.Dapr.DaprClient>();
        }
    }
}
