// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: dapr.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Dapr.Client.Grpc {
  /// <summary>
  /// Dapr definitions
  /// </summary>
  public static partial class Dapr
  {
    static readonly string __ServiceName = "dapr.Dapr";

    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.PublishEventEnvelope> __Marshaller_dapr_PublishEventEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.PublishEventEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.InvokeServiceEnvelope> __Marshaller_dapr_InvokeServiceEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.InvokeServiceEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope> __Marshaller_dapr_InvokeServiceResponseEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.InvokeBindingEnvelope> __Marshaller_dapr_InvokeBindingEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.InvokeBindingEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.GetStateEnvelope> __Marshaller_dapr_GetStateEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.GetStateEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.GetStateResponseEnvelope> __Marshaller_dapr_GetStateResponseEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.GetStateResponseEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.SaveStateEnvelope> __Marshaller_dapr_SaveStateEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.SaveStateEnvelope.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Dapr.Client.Grpc.DeleteStateEnvelope> __Marshaller_dapr_DeleteStateEnvelope = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Dapr.Client.Grpc.DeleteStateEnvelope.Parser.ParseFrom);

    static readonly grpc::Method<global::Dapr.Client.Grpc.PublishEventEnvelope, global::Google.Protobuf.WellKnownTypes.Empty> __Method_PublishEvent = new grpc::Method<global::Dapr.Client.Grpc.PublishEventEnvelope, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PublishEvent",
        __Marshaller_dapr_PublishEventEnvelope,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Dapr.Client.Grpc.InvokeServiceEnvelope, global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope> __Method_InvokeService = new grpc::Method<global::Dapr.Client.Grpc.InvokeServiceEnvelope, global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InvokeService",
        __Marshaller_dapr_InvokeServiceEnvelope,
        __Marshaller_dapr_InvokeServiceResponseEnvelope);

    static readonly grpc::Method<global::Dapr.Client.Grpc.InvokeBindingEnvelope, global::Google.Protobuf.WellKnownTypes.Empty> __Method_InvokeBinding = new grpc::Method<global::Dapr.Client.Grpc.InvokeBindingEnvelope, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "InvokeBinding",
        __Marshaller_dapr_InvokeBindingEnvelope,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Dapr.Client.Grpc.GetStateEnvelope, global::Dapr.Client.Grpc.GetStateResponseEnvelope> __Method_GetState = new grpc::Method<global::Dapr.Client.Grpc.GetStateEnvelope, global::Dapr.Client.Grpc.GetStateResponseEnvelope>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetState",
        __Marshaller_dapr_GetStateEnvelope,
        __Marshaller_dapr_GetStateResponseEnvelope);

    static readonly grpc::Method<global::Dapr.Client.Grpc.SaveStateEnvelope, global::Google.Protobuf.WellKnownTypes.Empty> __Method_SaveState = new grpc::Method<global::Dapr.Client.Grpc.SaveStateEnvelope, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveState",
        __Marshaller_dapr_SaveStateEnvelope,
        __Marshaller_google_protobuf_Empty);

    static readonly grpc::Method<global::Dapr.Client.Grpc.DeleteStateEnvelope, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteState = new grpc::Method<global::Dapr.Client.Grpc.DeleteStateEnvelope, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteState",
        __Marshaller_dapr_DeleteStateEnvelope,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Dapr.Client.Grpc.DaprReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Dapr</summary>
    public partial class DaprClient : grpc::ClientBase<DaprClient>
    {
      /// <summary>Creates a new client for Dapr</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public DaprClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Dapr that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DaprClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DaprClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected DaprClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Google.Protobuf.WellKnownTypes.Empty PublishEvent(global::Dapr.Client.Grpc.PublishEventEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PublishEvent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty PublishEvent(global::Dapr.Client.Grpc.PublishEventEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PublishEvent, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PublishEventAsync(global::Dapr.Client.Grpc.PublishEventEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PublishEventAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> PublishEventAsync(global::Dapr.Client.Grpc.PublishEventEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PublishEvent, null, options, request);
      }
      public virtual global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope InvokeService(global::Dapr.Client.Grpc.InvokeServiceEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeService(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope InvokeService(global::Dapr.Client.Grpc.InvokeServiceEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InvokeService, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope> InvokeServiceAsync(global::Dapr.Client.Grpc.InvokeServiceEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeServiceAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Dapr.Client.Grpc.InvokeServiceResponseEnvelope> InvokeServiceAsync(global::Dapr.Client.Grpc.InvokeServiceEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InvokeService, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InvokeBinding(global::Dapr.Client.Grpc.InvokeBindingEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeBinding(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty InvokeBinding(global::Dapr.Client.Grpc.InvokeBindingEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_InvokeBinding, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InvokeBindingAsync(global::Dapr.Client.Grpc.InvokeBindingEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InvokeBindingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> InvokeBindingAsync(global::Dapr.Client.Grpc.InvokeBindingEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_InvokeBinding, null, options, request);
      }
      public virtual global::Dapr.Client.Grpc.GetStateResponseEnvelope GetState(global::Dapr.Client.Grpc.GetStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Dapr.Client.Grpc.GetStateResponseEnvelope GetState(global::Dapr.Client.Grpc.GetStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Dapr.Client.Grpc.GetStateResponseEnvelope> GetStateAsync(global::Dapr.Client.Grpc.GetStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Dapr.Client.Grpc.GetStateResponseEnvelope> GetStateAsync(global::Dapr.Client.Grpc.GetStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetState, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SaveState(global::Dapr.Client.Grpc.SaveStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty SaveState(global::Dapr.Client.Grpc.SaveStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SaveState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SaveStateAsync(global::Dapr.Client.Grpc.SaveStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SaveStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> SaveStateAsync(global::Dapr.Client.Grpc.SaveStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SaveState, null, options, request);
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteState(global::Dapr.Client.Grpc.DeleteStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteState(global::Dapr.Client.Grpc.DeleteStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteState, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteStateAsync(global::Dapr.Client.Grpc.DeleteStateEnvelope request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteStateAsync(global::Dapr.Client.Grpc.DeleteStateEnvelope request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteState, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override DaprClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new DaprClient(configuration);
      }
    }

  }
}
#endregion
