// ------------------------------------------------------------------------
// Copyright 2026 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;
using Dapr.Common;
using Dapr.Common.Serialization;
using Dapr.StateManagement;
using Moq;

namespace Dapr.StateManagement.Test;

/// <summary>
/// Tests for <see cref="DaprStateManagementGrpcClient"/> focusing on argument validation and
/// helper methods that can be exercised without a live Dapr sidecar.
/// </summary>
public class DaprStateManagementGrpcClientTests
{
    private static DaprStateManagementGrpcClient CreateClient()
    {
        // Construct a gRPC channel pointing at a non-existent endpoint; we won't actually
        // call it in these unit tests — we only test argument validation paths.
        var channel = Grpc.Net.Client.GrpcChannel.ForAddress("http://localhost:50001");
        var grpcClient = new Autogenerated.Dapr.DaprClient(channel);
        return new DaprStateManagementGrpcClient(
            grpcClient,
            new HttpClient(),
            Mock.Of<IDaprRuntimeCapabilities>(),
            new JsonDaprSerializer(new JsonSerializerOptions(JsonSerializerDefaults.Web)));
    }

    // ── GetStateAsync argument validation ────────────────────────────────────

    [Fact]
    public async Task GetStateAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.GetStateAsync<string>(null!, "key", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetStateAsync_EmptyStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentException>(() =>
            client.GetStateAsync<string>(string.Empty, "key", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetStateAsync_NullKey_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.GetStateAsync<string>("store", null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── GetStateAndETagAsync argument validation ──────────────────────────────

    [Fact]
    public async Task GetStateAndETagAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.GetStateAndETagAsync<string>(null!, "key", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetStateAndETagAsync_NullKey_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.GetStateAndETagAsync<string>("store", null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── GetBulkStateAsync argument validation ────────────────────────────────

    [Fact]
    public async Task GetBulkStateAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.GetBulkStateAsync<string>(null!, ["key"], cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task GetBulkStateAsync_EmptyKeys_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentException>(() =>
            client.GetBulkStateAsync<string>("store", Array.Empty<string>(), cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── SaveStateAsync argument validation ───────────────────────────────────

    [Fact]
    public async Task SaveStateAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.SaveStateAsync(null!, "key", "value", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task SaveStateAsync_NullKey_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.SaveStateAsync("store", null!, "value", cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── TrySaveStateAsync argument validation ────────────────────────────────

    [Fact]
    public async Task TrySaveStateAsync_NullEtag_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.TrySaveStateAsync("store", "key", "value", null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── DeleteStateAsync argument validation ─────────────────────────────────

    [Fact]
    public async Task DeleteStateAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.DeleteStateAsync(null!, "key", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task DeleteStateAsync_NullKey_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.DeleteStateAsync("store", null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── TryDeleteStateAsync argument validation ───────────────────────────────

    [Fact]
    public async Task TryDeleteStateAsync_NullEtag_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.TryDeleteStateAsync("store", "key", null!, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── ExecuteStateTransactionAsync argument validation ─────────────────────

    [Fact]
    public async Task ExecuteStateTransactionAsync_EmptyOperations_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentException>(() =>
            client.ExecuteStateTransactionAsync("store", Array.Empty<StateTransactionRequest>(), cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task ExecuteStateTransactionAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        var ops = new[] { new StateTransactionRequest("key", null, StateOperationType.Delete) };
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.ExecuteStateTransactionAsync(null!, ops, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── QueryStateAsync argument validation ──────────────────────────────────

    [Fact]
    public async Task QueryStateAsync_NullStoreName_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            client.QueryStateAsync<string>(null!, "{}", cancellationToken: TestContext.Current.CancellationToken));
    }

    [Fact]
    public async Task QueryStateAsync_EmptyQuery_Throws()
    {
        using var client = CreateClient();
        await Assert.ThrowsAsync<ArgumentException>(() =>
            client.QueryStateAsync<string>("store", string.Empty, cancellationToken: TestContext.Current.CancellationToken));
    }

    // ── Model type tests ────────────────────────────────────────────────────

    [Fact]
    public void SaveStateItem_StoresAllProperties()
    {
        var metadata = new Dictionary<string, string> { ["key"] = "val" };
        var options = new StateOptions { Consistency = ConsistencyMode.Strong };
        var item = new SaveStateItem<string>("mykey", "myvalue", "etag1", options, metadata);

        Assert.Equal("mykey", item.Key);
        Assert.Equal("myvalue", item.Value);
        Assert.Equal("etag1", item.ETag);
        Assert.Same(options, item.StateOptions);
        Assert.Same(metadata, item.Metadata);
    }

    [Fact]
    public void BulkDeleteStateItem_StoresAllProperties()
    {
        var metadata = new Dictionary<string, string> { ["k"] = "v" };
        var options = new StateOptions { Concurrency = ConcurrencyMode.FirstWrite };
        var item = new BulkDeleteStateItem("k", "etag", options, metadata);

        Assert.Equal("k", item.Key);
        Assert.Equal("etag", item.ETag);
        Assert.Same(options, item.StateOptions);
        Assert.Same(metadata, item.Metadata);
    }

    [Fact]
    public void StateTransactionRequest_NullKey_Throws()
    {
        Assert.Throws<ArgumentNullException>(() =>
            new StateTransactionRequest(null!, null, StateOperationType.Upsert));
    }

    [Fact]
    public void StateQueryResponse_ExposesAllProperties()
    {
        var items = new List<StateQueryItem<string>>
        {
            new("k1", "v1", "e1", null)
        };
        var metadata = new Dictionary<string, string>();
        var response = new StateQueryResponse<string>(items, "token", metadata);

        Assert.Single(response.Results);
        Assert.Equal("token", response.Token);
        Assert.Same(metadata, response.Metadata);
    }
}
