<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks></TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auction.Next.FSharp.Example04.Actors\Auction.Next.FSharp.Example04.Actors.fsproj" />
    <ProjectReference Include="..\Auction.Next.FSharp.Example04.Glue\Auction.Next.FSharp.Example04.Glue.csproj" />
  </ItemGroup>

</Project>