// ------------------------------------------------------------------------
// Copyright 2026 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.AI.Conversation;

/// <summary>
/// Represents the breakdown of usage completion tokens used in a conversation.
/// </summary>
/// <param name="AcceptedPredictionTokens">When using predicted outputs, the number of tokens in the
/// prediction that appeared in the completion.</param>
/// <param name="AudioTokens">The audio input tokens generated by the model.</param>
/// <param name="ReasoningTokens">Tokens generated by the model for reasoning.</param>
/// <param name="RejectedPredictionTokens">When using predicted outputs, the number of tokens in the prediction that did not
/// appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion
/// tokens for purposes for billing, output, and context window limits.</param>
public sealed record UsageCompletionTokensDetails(
    ulong AcceptedPredictionTokens,
    ulong AudioTokens,
    ulong ReasoningTokens,
    ulong RejectedPredictionTokens)

{
    /// <summary>
    /// Creates an instance of <see cref="UsageCompletionTokensDetails"/> from the prototype value.
    /// </summary>
    /// <param name="proto">The gRPC response from the runtime to parse.</param>
    /// <returns>A new instance of <see cref="UsageCompletionTokensDetails"/>.</returns>
    internal static UsageCompletionTokensDetails?
        FromProto(ConversationResultAlpha2CompletionUsageCompletionTokensDetails? proto) =>
        proto is null
            ? null
            : new(
                proto.AcceptedPredictionTokens, proto.AudioTokens, proto.ReasoningTokens,
                proto.RejectedPredictionTokens);
}

