// using Autogenerated = Dapr.Client.Autogen.Grpc.v1;
//
// namespace Dapr.Messaging.PublishSubscribe;
//
// /// <summary>
// /// Builds a <see cref="DaprPublishSubscribeClient"/>.
// /// </summary>
// public sealed class DaprPublishSubscribeClientBuilder : DaprGenericClientBuilder<DaprPublishSubscribeClient>
// {
//     /// <summary>
//     /// Builds the client instance from the properties of the builder.
//     /// </summary>
//     /// <returns>The Dapr client instance.</returns>
//     /// <summary>
//     /// Builds the client instance from the properties of the builder.
//     /// </summary>
//     public override DaprPublishSubscribeClient Build()
//     {
//         var daprClientDependencies = BuildDaprClientDependencies();
//         var client = new Autogenerated.Dapr.DaprClient(daprClientDependencies.channel);
//
//         return new DaprPublishSubscribeGrpcClient(client);
//     }
// }
