using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Dapr.Actors.Generators
{
    /// <summary>
    /// Templates for generating source code.
    /// </summary>
    internal static partial class Templates
    {
        /// <summary>
        /// Returns the source text for the ActorMethodAttribute.
        /// </summary>
        /// <param name="generatorNamespace"></param>
        /// <returns></returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static SourceText ActorMethodAttributeSourceText(string generatorNamespace)
        {
            if (generatorNamespace == null)
            {
                throw new ArgumentNullException(nameof(generatorNamespace));
            }

            var source = $@"
// <auto-generated/>

#nullable enable

using System;

namespace {generatorNamespace}
{{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
    internal sealed class {Constants.ActorMethodAttributeTypeName} : Attribute
    {{
        public string? Name {{ get; set; }}
    }}
}}";

            return SourceText.From(
                SyntaxFactory.ParseCompilationUnit(source)
                    .NormalizeWhitespace()
                    .ToFullString(),
                Encoding.UTF8);
        }

        /// <summary>
        /// Returns the source text for the GenerateActorClientAttribute.
        /// </summary>
        /// <param name="generatorNamespace"></param>
        /// <returns></returns>
        /// <exception cref="ArgumentNullException"></exception>
        public static SourceText GenerateActorClientAttributeSourceText(string generatorNamespace)
        {
            if (generatorNamespace == null)
            {
                throw new ArgumentNullException(nameof(generatorNamespace));
            }

            string source = $@"
// <auto-generated/>

#nullable enable

using System;

namespace {generatorNamespace}
{{
    [AttributeUsage(AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class {Constants.GenerateActorClientAttributeTypeName} : Attribute
    {{
        public string? Name {{ get; set; }}

        public string? Namespace {{ get; set; }}
    }}
}}";

            return SourceText.From(
                SyntaxFactory.ParseCompilationUnit(source)
                    .NormalizeWhitespace()
                    .ToFullString(),
                Encoding.UTF8);
        }
    }
}
