// ------------------------------------------------------------------------
// Copyright 2026 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ------------------------------------------------------------------------

using System;
using System.Threading;
using System.Threading.Tasks;
using Dapr.Common;
using Grpc.Core;
using Moq;
using Xunit;
using Autogenerated = Dapr.Client.Autogen.Grpc.v1;

namespace Dapr.Client.Test;

public sealed class VersionAwareDaprClientFallbackTests
{
    [Fact]
    public async Task StartWorkflowAsync_WhenDiscoveryIsUnknownAndBetaIsUnavailable_FallsBackToAlpha()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var capabilities = CreateCapabilities(DaprRuntimeSupport.Unknown);
        var inner = new Mock<Autogenerated.Dapr.DaprClient>(MockBehavior.Strict);

        inner
            .Setup(client => client.StartWorkflowBeta1Async(
                It.IsAny<Autogenerated.StartWorkflowRequest>(),
                It.IsAny<CallOptions>()))
            .Throws(new RpcException(new Status(StatusCode.Unimplemented, "Beta method unavailable.")));

#pragma warning disable CS0612 // The generated selector intentionally invokes the obsolete runtime fallback.
        inner
            .Setup(client => client.StartWorkflowAlpha1Async(
                It.IsAny<Autogenerated.StartWorkflowRequest>(),
                It.IsAny<CallOptions>()))
            .Returns(CreateUnaryCall<Autogenerated.StartWorkflowResponse>());
#pragma warning restore CS0612

        var client = new VersionAwareDaprClient(inner.Object, capabilities.Object);

        var firstResponse = await client.StartWorkflowAsync(
            new Autogenerated.StartWorkflowRequest(),
            new CallOptions(cancellationToken: cancellationToken));
        var secondResponse = await client.StartWorkflowAsync(
            new Autogenerated.StartWorkflowRequest(),
            new CallOptions(cancellationToken: cancellationToken));

        Assert.NotNull(firstResponse);
        Assert.NotNull(secondResponse);
        capabilities.Verify(capability => capability.GetMethodSupportAsync(
            "dapr.proto.runtime.v1.Dapr/StartWorkflowBeta1",
            cancellationToken), Times.Once);
        capabilities.Verify(capability => capability.GetMethodSupportAsync(
            "dapr.proto.runtime.v1.Dapr/StartWorkflowAlpha1",
            cancellationToken), Times.Once);
        inner.Verify(client => client.StartWorkflowBeta1Async(
            It.IsAny<Autogenerated.StartWorkflowRequest>(),
            It.IsAny<CallOptions>()), Times.Once);
#pragma warning disable CS0612 // Verify that the cached obsolete fallback is invoked directly.
        inner.Verify(client => client.StartWorkflowAlpha1Async(
            It.IsAny<Autogenerated.StartWorkflowRequest>(),
            It.IsAny<CallOptions>()), Times.Exactly(2));
#pragma warning restore CS0612
    }

    [Fact]
    public async Task StartWorkflowAsync_WhenCatalogConfirmsBetaUnsupported_CallsAlphaDirectly()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var capabilities = new Mock<IDaprRuntimeCapabilities>(MockBehavior.Strict);
        capabilities
            .Setup(capability => capability.GetMethodSupportAsync(
                "dapr.proto.runtime.v1.Dapr/StartWorkflowBeta1",
                cancellationToken))
            .ReturnsAsync(DaprRuntimeSupport.Unsupported);
        capabilities
            .Setup(capability => capability.GetMethodSupportAsync(
                "dapr.proto.runtime.v1.Dapr/StartWorkflowAlpha1",
                cancellationToken))
            .ReturnsAsync(DaprRuntimeSupport.Supported);

        var inner = new Mock<Autogenerated.Dapr.DaprClient>(MockBehavior.Strict);
#pragma warning disable CS0612 // The generated selector intentionally invokes the obsolete runtime fallback.
        inner
            .Setup(client => client.StartWorkflowAlpha1Async(
                It.IsAny<Autogenerated.StartWorkflowRequest>(),
                It.IsAny<CallOptions>()))
            .Returns(CreateUnaryCall<Autogenerated.StartWorkflowResponse>());
#pragma warning restore CS0612

        var client = new VersionAwareDaprClient(inner.Object, capabilities.Object);

        var response = await client.StartWorkflowAsync(
            new Autogenerated.StartWorkflowRequest(),
            new CallOptions(cancellationToken: cancellationToken));

        Assert.NotNull(response);
        inner.Verify(client => client.StartWorkflowBeta1Async(
            It.IsAny<Autogenerated.StartWorkflowRequest>(),
            It.IsAny<CallOptions>()), Times.Never);
    }

    [Fact]
    public async Task StartWorkflowAsync_WhenBetaReturnsDaprProxyError_FallsBackToAlpha()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var capabilities = CreateCapabilities(DaprRuntimeSupport.Unknown);
        var inner = new Mock<Autogenerated.Dapr.DaprClient>(MockBehavior.Strict);
        inner
            .Setup(client => client.StartWorkflowBeta1Async(
                It.IsAny<Autogenerated.StartWorkflowRequest>(),
                It.IsAny<CallOptions>()))
            .Throws(new RpcException(new Status(
                StatusCode.Unknown,
                "cannot proxy request: missing dapr-callee-app-id or dapr-app-id metadata")));

#pragma warning disable CS0612 // The generated selector intentionally invokes the obsolete runtime fallback.
        inner
            .Setup(client => client.StartWorkflowAlpha1Async(
                It.IsAny<Autogenerated.StartWorkflowRequest>(),
                It.IsAny<CallOptions>()))
            .Returns(CreateUnaryCall<Autogenerated.StartWorkflowResponse>());
#pragma warning restore CS0612

        var client = new VersionAwareDaprClient(inner.Object, capabilities.Object);

        var response = await client.StartWorkflowAsync(
            new Autogenerated.StartWorkflowRequest(),
            new CallOptions(cancellationToken: cancellationToken));

        Assert.NotNull(response);
    }

    [Fact]
    public async Task ScheduleJobAsync_WhenDiscoveryIsUnknownAndStableIsUnavailable_FallsBackToAlpha()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var capabilities = CreateCapabilities(DaprRuntimeSupport.Unknown);
        var inner = new Mock<Autogenerated.Dapr.DaprClient>(MockBehavior.Strict);
        inner
            .Setup(client => client.ScheduleJobAsync(
                It.IsAny<Autogenerated.ScheduleJobRequest>(),
                It.IsAny<CallOptions>()))
            .Throws(new RpcException(new Status(StatusCode.Unimplemented, "Stable method unavailable.")));

#pragma warning disable CS0612 // The generated selector intentionally invokes the obsolete runtime fallback.
        inner
            .Setup(client => client.ScheduleJobAlpha1Async(
                It.IsAny<Autogenerated.ScheduleJobRequest>(),
                It.IsAny<CallOptions>()))
            .Returns(CreateUnaryCall<Autogenerated.ScheduleJobResponse>());
#pragma warning restore CS0612

        var client = new VersionAwareDaprClient(inner.Object, capabilities.Object);

        var firstResponse = await client.ScheduleJobAsync(
            new Autogenerated.ScheduleJobRequest(),
            new CallOptions(cancellationToken: cancellationToken));
        var secondResponse = await client.ScheduleJobAsync(
            new Autogenerated.ScheduleJobRequest(),
            new CallOptions(cancellationToken: cancellationToken));

        Assert.NotNull(firstResponse);
        Assert.NotNull(secondResponse);
        capabilities.Verify(capability => capability.GetMethodSupportAsync(
            "dapr.proto.runtime.v1.Dapr/ScheduleJob",
            cancellationToken), Times.Once);
        capabilities.Verify(capability => capability.GetMethodSupportAsync(
            "dapr.proto.runtime.v1.Dapr/ScheduleJobAlpha1",
            cancellationToken), Times.Once);
        inner.Verify(client => client.ScheduleJobAsync(
            It.IsAny<Autogenerated.ScheduleJobRequest>(),
            It.IsAny<CallOptions>()), Times.Once);
#pragma warning disable CS0612 // Verify that the cached obsolete fallback is invoked directly.
        inner.Verify(client => client.ScheduleJobAlpha1Async(
            It.IsAny<Autogenerated.ScheduleJobRequest>(),
            It.IsAny<CallOptions>()), Times.Exactly(2));
#pragma warning restore CS0612
    }

    [Fact]
    public async Task ConverseAsync_WhenDiscoveryIsUnknownAndAlpha2IsUnavailable_DoesNotGuessIncompatibleAlpha1()
    {
        var cancellationToken = TestContext.Current.CancellationToken;
        var capabilities = CreateCapabilities(DaprRuntimeSupport.Unknown);
        var inner = new Mock<Autogenerated.Dapr.DaprClient>(MockBehavior.Strict);
        inner
            .Setup(client => client.ConverseAlpha2Async(
                It.IsAny<Autogenerated.ConversationRequestAlpha2>(),
                It.IsAny<CallOptions>()))
            .Throws(new RpcException(new Status(StatusCode.Unimplemented, "Alpha2 method unavailable.")));

        var client = new VersionAwareDaprClient(inner.Object, capabilities.Object);

        var exception = await Assert.ThrowsAsync<NotSupportedException>(() => client.ConverseAsync(
            new Autogenerated.ConversationRequestAlpha2(),
            new CallOptions(cancellationToken: cancellationToken)));

        Assert.Contains("runtime method discovery is unavailable", exception.Message);
        Assert.Contains("ConverseAlpha1", exception.Message);
#pragma warning disable CS0612 // Verify that the obsolete incompatible fallback was not invoked.
        inner.Verify(client => client.ConverseAlpha1Async(
            It.IsAny<Autogenerated.ConversationRequest>(),
            It.IsAny<CallOptions>()), Times.Never);
#pragma warning restore CS0612
    }

    private static Mock<IDaprRuntimeCapabilities> CreateCapabilities(DaprRuntimeSupport support)
    {
        var capabilities = new Mock<IDaprRuntimeCapabilities>(MockBehavior.Strict);
        capabilities
            .Setup(capability => capability.GetMethodSupportAsync(
                It.IsAny<string>(),
                It.IsAny<CancellationToken>()))
            .ReturnsAsync(support);
        return capabilities;
    }

    private static AsyncUnaryCall<TResponse> CreateUnaryCall<TResponse>()
        where TResponse : new()
    {
        return new AsyncUnaryCall<TResponse>(
            Task.FromResult(new TResponse()),
            Task.FromResult(new Metadata()),
            () => Status.DefaultSuccess,
            () => new Metadata(),
            () => { });
    }
}
