// ------------------------------------------------------------------------
// Copyright 2025 The Dapr Authors
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//  ------------------------------------------------------------------------

using System.Text;
using Dapr.Jobs;
using Dapr.Jobs.Extensions;
using Dapr.Jobs.Models;
using Dapr.Jobs.Models.Responses;
using Dapr.Testcontainers.Common;
using Dapr.Testcontainers.Harnesses;
using Dapr.Testcontainers.Xunit.Attributes;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Dapr.IntegrationTest.Jobs;

/// <summary>
/// Validates that the Jobs SDK operates correctly across Dapr runtime versions that
/// surface the Jobs gRPC API at different maturity levels:
///
///   1.16 / 1.17 — ScheduleJobAlpha1 / GetJobAlpha1 / DeleteJobAlpha1  (Alpha1 suffix)
///   1.18+        — ScheduleJob / GetJob / DeleteJob                     (Stable, no suffix)
///
/// The version-aware client generated by DaprVersionAwareGenerator performs a gRPC
/// reflection check at call time and routes to the highest-maturity method the
/// connected runtime supports, falling back to the Alpha1 variants when the stable
/// methods are absent.  These tests exercise that routing by running against a live
/// sidecar and asserting functional correctness; a test tagged [MinimumDaprRuntimeFact("1.16")]
/// exercises the Alpha1 fallback path on older runtimes while the same operations
/// transparently use the Stable path when run against 1.18+.
/// </summary>
public sealed class JobVersionCompatibilityTests
{
    // -----------------------------------------------------------------------
    // Alpha1 path (Dapr 1.16 – 1.17): the version-aware client falls back to
    // ScheduleJobAlpha1 / GetJobAlpha1 / DeleteJobAlpha1 because the stable
    // methods are not yet exposed by the runtime.
    // On 1.18+ these same tests run via the Stable gRPC methods, proving the
    // transparent upgrade path works correctly.
    // -----------------------------------------------------------------------

    [MinimumDaprRuntimeFact("1.16")]
    public async Task AlphaRuntime_ScheduleThenGetJob_RoundTripSucceeds()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"compat-get-{Guid.NewGuid():N}";

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        var payload = "version-compat-payload"u8.ToArray();
        var schedule = DaprJobSchedule.FromDuration(TimeSpan.FromHours(1));

        await client.ScheduleJobAsync(jobName, schedule, payload, repeats: 5, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var details = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);

        Assert.NotNull(details);
        Assert.Equal(5, details.RepeatCount);
        Assert.NotNull(details.Payload);
        Assert.Equal(Encoding.UTF8.GetString(payload), Encoding.UTF8.GetString(details.Payload));

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);
    }

    [MinimumDaprRuntimeFact("1.16")]
    public async Task AlphaRuntime_DeleteJob_JobNoLongerExists()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"compat-delete-{Guid.NewGuid():N}";

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromHours(1)),
            overwrite: true, cancellationToken: TestContext.Current.CancellationToken);

        var beforeDelete = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);
        Assert.NotNull(beforeDelete);

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);

        await Assert.ThrowsAsync<DaprException>(() =>
            client.GetJobAsync(jobName, TestContext.Current.CancellationToken));
    }

    [MinimumDaprRuntimeFact("1.16")]
    public async Task AlphaRuntime_ScheduleAndReceiveJob_PayloadDelivered()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"compat-recv-{Guid.NewGuid():N}";

        var tcs = new TaskCompletionSource<(string jobName, byte[] payload)>(
            TaskCreationOptions.RunContinuationsAsynchronously);

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .ConfigureApp(app =>
            {
                app.MapDaprScheduledJobHandler((string incomingJobName, ReadOnlyMemory<byte> payload,
                    ILogger<JobVersionCompatibilityTests>? logger, CancellationToken _) =>
                {
                    logger?.LogInformation("Compat test received job {Job}", incomingJobName);
                    tcs.TrySetResult((incomingJobName, payload.ToArray()));
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        var payload = "compat-hello"u8.ToArray();
        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromSeconds(2)),
            payload, repeats: 1, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var received = await tcs.Task.WaitAsync(TimeSpan.FromSeconds(30),
            TestContext.Current.CancellationToken);
        Assert.Equal(jobName, received.jobName);
        Assert.Equal(Encoding.UTF8.GetString(payload), Encoding.UTF8.GetString(received.payload));
    }

    // -----------------------------------------------------------------------
    // Stable path (Dapr 1.18+): the version-aware client detects that the
    // Stable gRPC methods (ScheduleJob / GetJob / DeleteJob) are present and
    // uses them directly without falling back to the Alpha1 variants.
    // -----------------------------------------------------------------------

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_ScheduleThenGetJob_RoundTripSucceeds()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-get-{Guid.NewGuid():N}";

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        var payload = "stable-payload"u8.ToArray();
        var schedule = DaprJobSchedule.FromDuration(TimeSpan.FromHours(1));

        await client.ScheduleJobAsync(jobName, schedule, payload, repeats: 3, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var details = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);

        Assert.NotNull(details);
        Assert.Equal(3, details.RepeatCount);
        Assert.NotNull(details.Payload);
        Assert.Equal(Encoding.UTF8.GetString(payload), Encoding.UTF8.GetString(details.Payload));

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);
    }

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_DeleteJob_JobNoLongerExists()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-delete-{Guid.NewGuid():N}";

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromHours(1)),
            overwrite: true, cancellationToken: TestContext.Current.CancellationToken);

        var beforeDelete = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);
        Assert.NotNull(beforeDelete);

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);

        await Assert.ThrowsAsync<DaprException>(() =>
            client.GetJobAsync(jobName, TestContext.Current.CancellationToken));
    }

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_ScheduleAndReceiveJob_PayloadDelivered()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-recv-{Guid.NewGuid():N}";

        var tcs = new TaskCompletionSource<(string jobName, byte[] payload)>(
            TaskCreationOptions.RunContinuationsAsynchronously);

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .ConfigureApp(app =>
            {
                app.MapDaprScheduledJobHandler((string incomingJobName, ReadOnlyMemory<byte> payload,
                    ILogger<JobVersionCompatibilityTests>? logger, CancellationToken _) =>
                {
                    logger?.LogInformation("Stable compat test received job {Job}", incomingJobName);
                    tcs.TrySetResult((incomingJobName, payload.ToArray()));
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        var payload = "stable-hello"u8.ToArray();
        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromSeconds(2)),
            payload, repeats: 1, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var received = await tcs.Task.WaitAsync(TimeSpan.FromSeconds(30),
            TestContext.Current.CancellationToken);
        Assert.Equal(jobName, received.jobName);
        Assert.Equal(Encoding.UTF8.GetString(payload), Encoding.UTF8.GetString(received.payload));
    }

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_OverwriteJob_UpdatesTakeEffect()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-overwrite-{Guid.NewGuid():N}";

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        var originalPayload = "original"u8.ToArray();
        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromHours(1)),
            originalPayload, repeats: 2, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var original = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);
        Assert.Equal(2, original.RepeatCount);

        var updatedPayload = "updated"u8.ToArray();
        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromMinutes(30)),
            updatedPayload, repeats: 7, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var updated = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);
        Assert.Equal(7, updated.RepeatCount);
        Assert.NotNull(updated.Payload);
        Assert.Equal(Encoding.UTF8.GetString(updatedPayload), Encoding.UTF8.GetString(updated.Payload));

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);
    }

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_ScheduleJobWithDropFailurePolicy_PolicyPersistedAndJobDroppedAfterExecution()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-drop-{Guid.NewGuid():N}";

        var tcs = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .ConfigureApp(app =>
            {
                app.MapDaprScheduledJobHandler((string incomingJobName, ReadOnlyMemory<byte> _,
                    ILogger<JobVersionCompatibilityTests>? logger, CancellationToken _) =>
                {
                    logger?.LogInformation("Stable drop-policy test received job {Job}", incomingJobName);
                    tcs.TrySetResult(incomingJobName);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromSeconds(2)),
            failurePolicyOptions: new JobFailurePolicyDropOptions(), repeats: 1, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var received = await tcs.Task.WaitAsync(TimeSpan.FromSeconds(30),
            TestContext.Current.CancellationToken);
        Assert.Equal(jobName, received);

        var ex = await Assert.ThrowsAsync<DaprException>(() =>
            client.GetJobAsync(jobName, TestContext.Current.CancellationToken));
        Assert.NotNull(ex.InnerException);
        Assert.Contains("job not found", ex.InnerException.Message);
    }

    [MinimumDaprRuntimeFact("1.18")]
    public async Task StableRuntime_ScheduleJobWithConstantFailurePolicy_PolicyPersistedCorrectly()
    {
        var componentsDir = TestDirectoryManager.CreateTestDirectory("jobs-component");
        var jobName = $"stable-constant-{Guid.NewGuid():N}";

        var tcs = new TaskCompletionSource<string>(TaskCreationOptions.RunContinuationsAsynchronously);

        await using var environment = await DaprTestEnvironment.CreateWithPooledNetworkAsync(
            cancellationToken: TestContext.Current.CancellationToken);
        await environment.StartAsync(TestContext.Current.CancellationToken);

        var harness = new DaprHarnessBuilder(componentsDir)
            .WithEnvironment(environment)
            .BuildJobs();
        await using var testApp = await DaprHarnessBuilder.ForHarness(harness)
            .ConfigureServices(builder =>
            {
                builder.Services.AddDaprJobsClient(configure: (sp, clientBuilder) =>
                {
                    var config = sp.GetRequiredService<IConfiguration>();
                    var grpcEndpoint = config["DAPR_GRPC_ENDPOINT"];
                    var httpEndpoint = config["DAPR_HTTP_ENDPOINT"];
                    if (!string.IsNullOrEmpty(grpcEndpoint))
                        clientBuilder.UseGrpcEndpoint(grpcEndpoint);
                    if (!string.IsNullOrEmpty(httpEndpoint))
                        clientBuilder.UseHttpEndpoint(httpEndpoint);
                });
            })
            .ConfigureApp(app =>
            {
                app.MapDaprScheduledJobHandler((string incomingJobName, ReadOnlyMemory<byte> _,
                    ILogger<JobVersionCompatibilityTests>? logger, CancellationToken _) =>
                {
                    logger?.LogInformation("Stable constant-policy test received job {Job}", incomingJobName);
                    tcs.TrySetResult(incomingJobName);
                });
            })
            .BuildAndStartAsync();

        using var scope = testApp.CreateScope();
        var client = scope.ServiceProvider.GetRequiredService<DaprJobsClient>();

        const int maxRetries = 2;
        var constantPolicy = new JobFailurePolicyConstantOptions(TimeSpan.FromSeconds(5))
        {
            MaxRetries = maxRetries
        };

        await client.ScheduleJobAsync(jobName, DaprJobSchedule.FromDuration(TimeSpan.FromSeconds(2)),
            failurePolicyOptions: constantPolicy, repeats: 10, overwrite: true,
            cancellationToken: TestContext.Current.CancellationToken);

        var received = await tcs.Task.WaitAsync(TimeSpan.FromSeconds(30),
            TestContext.Current.CancellationToken);
        Assert.Equal(jobName, received);

        var details = await client.GetJobAsync(jobName, TestContext.Current.CancellationToken);
        Assert.NotNull(details.FailurePolicy);
        Assert.Equal(JobFailurePolicy.Constant, details.FailurePolicy.Type);
        if (details.FailurePolicy is ConfiguredConstantFailurePolicy policy)
        {
            Assert.True(policy.HasMaxRetries);
            Assert.Equal(maxRetries, policy.MaxRetries);
            Assert.Equal(TimeSpan.FromSeconds(5), policy.Duration);
        }
        else
        {
            Assert.Fail("Expected a ConfiguredConstantFailurePolicy.");
        }

        await client.DeleteJobAsync(jobName, TestContext.Current.CancellationToken);
    }
}
